name: trader

services:
  db:
    image: postgres
    restart: always
    env_file:
      - config/.env
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - db
    ports:
      - 8081:8080

  trader:
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    volumes:
      - ./config/.env:/app/config/.env:ro

volumes:
  postgres-data: