name: trader

services:
  db:
    image: postgres
    restart: always
    env_file:
      - config/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - /home/artufi/trading/data/postgresql:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - db
    ports:
      - 8080:8080

  trader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - /home/artufi/trading/data/trader/:/home/artufi/trading/apps/trader/app.log

volumes:
  postgres-data: